# Generated by Django 5.0.6 on 2024-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0006_chords_designation'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_songs',
            field=models.ManyToManyField(related_name='users', to='guitar.songs', verbose_name='Избранные песни'),
        ),
    ]
