# Generated by Django 5.0.6 on 2024-07-16 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guitar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='user_author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='songs',
            index=models.Index(fields=['-time_create'], name='guitar_song_time_cr_ad7a49_idx'),
        ),
    ]
