# Generated by Django 5.0.6 on 2024-07-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chords',
            name='chord_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='chords_images', verbose_name='Картинка аккорда'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='chords',
            field=models.ManyToManyField(related_name='songs', to='guitar.chords', verbose_name='Аккорды'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст песни'),
        ),
    ]
