# Generated by Django 5.0.6 on 2024-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0002_rename_post_sings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sings',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='sings',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='sings',
            index=models.Index(fields=['-time_create'], name='guitar_sing_time_cr_fbcd32_idx'),
        ),
    ]
