# Generated by Django 5.0.6 on 2024-07-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0003_chords_chord_image_alter_songs_chords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChordsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='chords',
            name='chords_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chords', to='guitar.chordsgroup'),
        ),
    ]
