# Generated by Django 5.0.6 on 2024-05-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0003_alter_sings_options_sings_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sings',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
