# Generated by Django 5.0.6 on 2024-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0004_alter_sings_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sings',
            name='is_published',
            field=models.BooleanField(choices=[('0', 'Черновик'), ('1', 'Опубликовано')], default='0'),
        ),
    ]
