# Generated by Django 5.0.6 on 2024-07-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0004_chordsgroup_chords_chords_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chordsgroup',
            name='group_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='chords_group_images'),
        ),
    ]
