# Generated by Django 5.0.6 on 2024-05-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0006_difficulty_sings_difficult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sings',
            name='difficult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitar.difficulty'),
        ),
    ]
