# Generated by Django 5.0.6 on 2024-05-30 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0007_alter_difficulty_slug_alter_sings_difficult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sings',
            name='difficult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sings', to='guitar.difficulty'),
        ),
        migrations.AddField(
            model_name='sings',
            name='chords',
            field=models.ManyToManyField(related_name='sings', to='guitar.chords'),
        ),
    ]
