# Generated by Django 5.0.6 on 2024-07-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0011_alter_authors_options_alter_difficulty_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sings',
            new_name='Songs',
        ),
    ]
