# Generated by Django 5.0.6 on 2024-07-13 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0012_auto_20240709_1410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='songs',
            new_name='guitar_song_time_cr_ad7a49_idx',
            old_name='guitar_sing_time_cr_fbcd32_idx',
        ),
        migrations.AddField(
            model_name='songs',
            name='user_author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='guitar.authors', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='chords',
            field=models.ManyToManyField(related_name='songs', to='guitar.chords'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='difficult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='guitar.difficulty', verbose_name='Сложность'),
        ),
    ]
